import AiInputForm from "./_components/ai-generate-form";
import { AccordionFAQ } from "@/components/common/faq";
import MusicCards from "./_components/music-card";
import MusicStyle from "./_components/music-style";
import SunoDisplay from "./_components/suno-display";

export default function Home() {
  return (
    <main className="mt-10 min-h-screen">
      <h1 className="pt-10 text-center font-bold md:text-3xl">Suno AI Music</h1>

      <p className="mx-auto mt-3 w-full max-w-md text-center text-muted-foreground">
        Generate Lyrics, Download songs and listern songs generated by Suno AI
        Music
      </p>
      <SunoDisplay />

      <MusicStyle />
      {/* <HoverMusicCard /> */}

      <AccordionFAQ />
    </main>
  );
}
