/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8N1qPxMC0Xv
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function HoverMusicCard() {
  return (
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 focus:not-sr-only" href="#">
          Listen
        </Link>
        <div className="relative overflow-hidden aspect-poster">
          <img
            alt="Cover image"
            className="object-cover w-full h-ful aspect-poster"
            height={225}
            src="/placeholder.svg"
            width={400}
          />
        </div>
        <div className="p-4">
          <div className="text-sm font-medium tracking-wide uppercase text-gray-500">Single</div>
          <div className="font-semibold">Call Me Tonight</div>
          <div className="text-sm text-gray-500">by The Vibes</div>
          <div className="absolute inset-0 flex items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Like
            </Button>
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 focus:not-sr-only" href="#">
          Listen
        </Link>
        <div className="relative overflow-hidden aspect-poster">
          <img
            alt="Cover image"
            className="object-cover w-full h-ful aspect-poster"
            height={225}
            src="/placeholder.svg"
            width={400}
          />
        </div>
        <div className="p-4">
          <div className="text-sm font-medium tracking-wide uppercase text-gray-500">Album</div>
          <div className="font-semibold">Sunset Groove</div>
          <div className="text-sm text-gray-500">by The Beachcombers</div>
          <div className="absolute inset-0 flex items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Like
            </Button>
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 focus:not-sr-only" href="#">
          Listen
        </Link>
        <div className="relative overflow-hidden aspect-poster">
          <img
            alt="Cover image"
            className="object-cover w-full h-ful aspect-poster"
            height={225}
            src="/placeholder.svg"
            width={400}
          />
        </div>
        <div className="p-4">
          <div className="text-sm font-medium tracking-wide uppercase text-gray-500">Podcast</div>
          <div className="font-semibold">Morning Coffee</div>
          <div className="text-sm text-gray-500">by Ava & James</div>
          <div className="absolute inset-0 flex items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Like
            </Button>
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 focus:not-sr-only" href="#">
          Listen
        </Link>
        <div className="relative overflow-hidden aspect-poster">
          <img
            alt="Cover image"
            className="object-cover w-full h-ful aspect-poster"
            height={225}
            src="/placeholder.svg"
            width={400}
          />
        </div>
        <div className="p-4">
          <div className="text-sm font-medium tracking-wide uppercase text-gray-500">Single</div>
          <div className="font-semibold">City Lights</div>
          <div className="text-sm text-gray-500">by The Neon Stars</div>
          <div className="absolute inset-0 flex items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Like
            </Button>
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <Link className="absolute inset-0 focus:not-sr-only" href="#">
          Listen
        </Link>
        <div className="relative overflow-hidden aspect-poster">
          <img
            alt="Cover image"
            className="object-cover w-full h-ful aspect-poster"
            height={225}
            src="/placeholder.svg"
            width={400}
          />
        </div>
        <div className="p-4">
          <div className="text-sm font-medium tracking-wide uppercase text-gray-500">Album</div>
          <div className="font-semibold">Dreamscapes</div>
          <div className="text-sm text-gray-500">by Harmony Ensemble</div>
          <div className="absolute inset-0 flex items-center justify-center gap-4 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Like
            </Button>
            <Button className="translate-x-[-10px]" size="sm" variant="outline">
              Add to Library
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
