import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export function AccordionFAQ() {
  const qa = [
    {
      question: "What is Suno AI Music and how does it work?",
      answer:
        "Suno AI Music is a web-based text-to-music generator that creates full songs in seconds from a simple text prompt. It uses a combination of large language models and diffusion models to construct original songs and lyrics based on user prompts, much like how generative AI tools like ChatGPT predict text sequences.",
    },
    {
      question: "How can I use Suno AI Music to generate a song?",
      answer:
        "To generate a song with Suno AI Music, you need to visit the Suno website, create an account, and go to the 'Create' section. There, you'll enter a description for your song, including the genre and topic, and Suno will generate a song based on your input. The free version allows up to 50 credits per day, which translates to ten songs.",
    },
    {
      question:
        "What are the differences between the free and Pro plans for Suno AI Music?",
      answer:
        "The free version of Suno AI Music allows you to generate up to 10 songs per day with limitations on commercial use. The Pro plan, at a cost of $8 per month, provides enough credits for 500 songs per day and permits commercial use of the generated music, such as on YouTube or streaming platforms like Spotify and Apple Music.",
    },
    {
      question: "Who owns the rights to the music generated by Suno AI Music?",
      answer:
        "For users with a Pro or Premier plan, they own the songs generated using Suno AI Music, provided they pay for the respective plan. Free users, however, do not own the rights to the songs they generate. Copyright ownership is a complex and evolving area of law, and Suno recommends consulting an attorney for the latest legal guidance on AI-generated music.",
    },
    {
      question:
        "How does Suno AI Music's V3 model improve on previous versions?",
      answer:
        "The V3 model of Suno AI Music introduces the ability to create full two-minute songs with a free account and offers more styles and genres, enhancing its versatility. It also provides better tools for polishing the results and the possibility to extend song lengths by generating new sections and stitching them together.",
    },
  ];

  return (
    <div className="mx-auto max-w-3xl">
      <h2 className="mt-[10rem]  text-2xl font-bold tracking-tight duration-1000 animate-in slide-in-from-bottom-6 lg:text-3xl">
        Questions & Answers
      </h2>
      <p className=" text-[16px] leading-7 text-muted-foreground">
        Json Translate Q&A
      </p>

      <Accordion type="single" collapsible className="">
        {qa.map((qa) => (
          <AccordionItem key={qa.question} value={qa.question}>
            <AccordionTrigger>{qa.question}</AccordionTrigger>
            <AccordionContent>{qa.answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}
