import React from "react";
import { Icons } from "./icons";
import Link from "next/link";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "../ui/dialog";

type Props = {};

export default function Footer({}: Props) {
  return (
    <footer className="container   mt-20 flex w-full flex-wrap  gap-10   px-8 py-12">
      <div className="mr-auto flex flex-1 flex-col">
        <p className="flex-1">
          <span>Suno AI Music</span>
        </p>
        <div className="flex items-center gap-1">
          <Link
            target="_blank"
            href="https://twitter.com/abc30037274"
            className=" rounded p-2 transition-colors duration-150 hover:bg-slate-200"
          >
            <Icons.X className="h-4 w-4" />
          </Link>
          <Link
            target="_blank"
            href="https://github.com/tonyljx/"
            className="rounded p-2 transition-colors duration-150 hover:bg-slate-200"
          >
            <Icons.gitHub className="h-4 w-4" />
          </Link>
        </div>
      </div>

      <div className="flex flex-1 gap-32">
        <div className="flex flex-col gap-3">
          <p className="font-bold">Product</p>
          <Link
            href="#"
            target="_blank"
            className="transition-colors duration-200 hover:text-blue-500"
          >
            Generate Lyrics
          </Link>

          <Link
            href="#"
            className="transition-colors duration-200 hover:text-blue-500"
          >
            Download Music
          </Link>

          <Link
            href="#"
            target="_blank"
            className="transition-colors duration-200 hover:text-blue-500"
          >
            View Music generated by suno
          </Link>
        </div>
        <div className="flex flex-col gap-3">
          <p className="font-bold">Resources</p>
          <a
            href="https://cartoongen.com"
            className="transition-colors duration-200 hover:text-blue-500"
          >
            AI Cartoon Generator
          </a>
        </div>
      </div>
    </footer>
  );
}
